# Generated by Django 3.0.4 on 2020-03-22 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(max_length=700, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/perfil', verbose_name='usuario avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mi_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
